// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadDecisionOption } from "./ThreadDecisionOption";
import type { ThreadDecisionStatus } from "./ThreadDecisionStatus";
import type { ThreadDecisionUrgency } from "./ThreadDecisionUrgency";

export type ThreadDecision = { id: string, threadId: string, title: string, description: string, urgency: ThreadDecisionUrgency, status: ThreadDecisionStatus, options: Array<ThreadDecisionOption>, recommendation: string | null, sourceTurnId: string | null, resolvedAt: number | null, resolution: string | null, selectedOptionId: string | null, };
