// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadDecision } from "./ThreadDecision";
import type { ThreadRequirementStatus } from "./ThreadRequirementStatus";

export type ThreadRequirement = { threadId: string, objective: string | null, status: ThreadRequirementStatus, summary: string, decisions: Array<ThreadDecision>, updatedAt: number | null, };
