// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadDecisionStatus } from "./ThreadDecisionStatus";
import type { ThreadDecisionUrgency } from "./ThreadDecisionUrgency";

export type ThreadDecisionListParams = { threadId: string, status?: ThreadDecisionStatus | null, urgency?: ThreadDecisionUrgency | null, };
